#!/usr/bin/env python3

import sys
from punchkicker import env

node = env.node

if "shell" not in node.roles:
    sys.exit(0)

packages = [
    "docs", "dash-doc", "busybox-doc", # man command and manual pages
    "bash", "gnupg", "libqrencode-tools",
    "utmps", "procps-ng", "jq", "yq"
]

env.apk_add(*packages)

env.run_with_print(["setup-utmp"])
