#!/usr/bin/env python3

import sys, os
from punchkicker import env

node = env.node

if "shell" not in node.roles and "wireguard" not in node.roles:
    sys.exit(0)

srcfn = os.path.join("1password", "op." + os.uname().machine)
env.resource_file(srcfn, "/usr/local/bin/op", mode=0o755, user="root", group="root")
