#!/usr/bin/env python3

import sys, os, shutil
from punchkicker import env

node = env.node

if "shell" not in node.roles and "wireguard" not in node.roles:
    sys.exit(0)

env.apk_add("wireguard-tools")

with open("/etc/sysctl.d/ip4-routing.conf", "w") as f:
    f.write("# Enable IP forwarding, for WireGuard\n")
    f.write("net.ipv4.ip_forward=1\n")

env.run_with_print(["sysctl", "-w", "net.ipv4.ip_forward=1"], indent=8)

env.mkdir_p("/etc/wireguard")
os.chmod("/etc/wireguard", 0o700)

shutil.copytree("/home/app/wireguard", "/etc/wireguard", symlinks=True, dirs_exist_ok=True)

